package ch.conceptforge.exerciceservlettes1;
// Generated 27 mars 2018 10:17:52 by Hibernate Tools 4.3.1



/**
 * Employesdetails generated by hbm2java
 */
public class Employesdetails  implements java.io.Serializable {


     private Integer id;
     private String ename;
     private String enumber;

    public Employesdetails() {
    }

    public Employesdetails(String ename, String enumber) {
       this.ename = ename;
       this.enumber = enumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getEnumber() {
        return this.enumber;
    }
    
    public void setEnumber(String enumber) {
        this.enumber = enumber;
    }




}


